### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by markitosgv** [KnlnKS/resume-parser#10]
I notice that isn't working,  @KnlnKS  do you think is possible to fix it?

**Comment by bennett1412** [comment]
is the api completely unavailable? or can it still be used partly, im asking because your website seems to be working

**Comment by KnlnKS** [comment]
The API can only be used partly to parse basic info like name, number, email, socials, and last job. Even though it may not be as much as before, I believe the site still has some use as it shows you if your resume parses at all.

**Comment by bennett1412** [comment]
thanks for replying,
