### ISSUE TITLE
School not listed as current even though current date is between start and end of the program

### ISSUE THREAD

**Issue by michelececcacci** [KnlnKS/resume-parser#7]
Not sure if this is intended,  but today's date(19/02/2022 ) is between the start and end of my degree, but the degree is not listed as current.

![image](https://user-images.githubusercontent.com/75946413/154813134-316fbf97-f20c-483a-bfad-16481b212772.png)

**Comment by KnlnKS** [comment]
The site merely uses Lever's API and displays the results. At the moment this is how Lever seems to parse education.

**Comment by michelececcacci** [comment]
Perfect, i just wanted to point it out. I looked at the source and couldn't find any kind of processing doen by the app, but I thought maybe i missed something. Thanks a lot for the answer
