### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by cherud2** [KnlnKS/resume-parser#9]
hey,
it doesn't seem to parse the entire resume. I've tried it on multiple resumes and the output in the screenshot below is all it returns

<img width="804" alt="Screen Shot 2022-04-17 at 4 59 31 PM" src="https://user-images.githubusercontent.com/103903748/163731958-490807c0-e499-443c-8393-27a68b037fa9.png">

**Comment by bballamudi** [comment]
So this has been my experience as well. This leaky api has been pretty much been acknowledged by fiver for at least couple of years since this became viral on reddit years ago. And it seems they have just got around to fix it. So I guess the free ride has come to an end now.

**Comment by KnlnKS** [comment]
Yes as @bballamudi has mentioned, the Lever api has changed its output. So this is now all the data we get.
